---
kind: pipeline
type: docker
name: deploy-dev
steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: 10.8.18.18
      username: rakhats
      password: pepl2302
      port: 22
      script:
        - cd peplink-forum
        - git reset --hard
        - git checkout dev
        - git pull
        - rm -rf node_modules
        - yarn install -s
        - yarn build:dev
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: di-drone
      template: >
        {{#if build.pull }}
          *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
          *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        <{{ build.link }}|Visit build page ↗>
trigger:
  branch:
    - dev
---
kind: pipeline
type: docker
name: deploy-hubstag
steps:
  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host: 10.8.18.19
      username: rakhats
      password: pepl2302
      port: 22
      script:
        - cd hubstag/peplink-forum/
        - git reset --hard
        - git checkout hubstag
        - git pull
        - rm -rf node_modules
        - yarn install -s
        - yarn build:hubstag
        - cd ~/private_key/
        - scp -r -i ./private.pem ../hubstag/peplink-forum/build/* ivanlau@10.82.0.38:/home/ivanlau/forumstag/deploy/
  - name: slack
    image: plugins/slack
    settings:
      webhook: https://hooks.slack.com/services/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
      channel: di-drone
      template: >
        {{#if build.pull }}
          *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}*: <https://github.com/{{ repo.owner }}/{{ repo.name }}/pull/{{ build.pull }}|Pull Request #{{ build.pull }}>
        {{else}}
          *{{#success build.status}}✔{{ else }}✘{{/success}} {{ uppercasefirst build.status }}: Build #{{ build.number }}* (type: `{{ build.event }}`)
        {{/if}}
        Commit: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}>
        Branch: <https://github.com/{{ repo.owner }}/{{ repo.name }}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        <{{ build.link }}|Visit build page ↗>
trigger:
  branch:
    - hubstag
